### ISSUE TITLE
Catch path in tests/ReaderTest.cpp

### ISSUE THREAD

**Issue by shadisharba** [dbeurle/GmshReader#9]
I think that the catch path in missing in `tests/ReaderTest.cpp`. Maybe use `#include <catch/catch.hpp>` instead of `#include <catch.hpp>`?

**Comment by dbeurle** [comment]
You're right.  This hasn't been updated recently, maybe I need to get Travis to compile it periodically.

I can put together a PR this afternoon if you like?

**Comment by dbeurle** [comment]
Done.
